// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiIflH0xM1w47n4Uygte2ZqPWyfoaOyvo',
    appId: '1:593158168216:web:6df1970cf5b3e802fb7aed',
    messagingSenderId: '593158168216',
    projectId: 'seesooq-98502',
    authDomain: 'seesooq-98502.firebaseapp.com',
    storageBucket: 'seesooq-98502.appspot.com',
    measurementId: 'G-YB4421BBTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCclsAkniTYbIFk4EhfHw6YsrmpIzIwXlg',
    appId: '1:593158168216:android:44f038b0755bf173fb7aed',
    messagingSenderId: '593158168216',
    projectId: 'seesooq-98502',
    storageBucket: 'seesooq-98502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK2ks4GY3dUwBccI1uqgeIVll2dYBCb0E',
    appId: '1:593158168216:ios:86e5585456dbece8fb7aed',
    messagingSenderId: '593158168216',
    projectId: 'seesooq-98502',
    storageBucket: 'seesooq-98502.appspot.com',
    iosBundleId: 'com.seesooq.opensooq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK2ks4GY3dUwBccI1uqgeIVll2dYBCb0E',
    appId: '1:593158168216:ios:064cd996a7500bdcfb7aed',
    messagingSenderId: '593158168216',
    projectId: 'seesooq-98502',
    storageBucket: 'seesooq-98502.appspot.com',
    iosBundleId: 'com.example.opensooq.RunnerTests',
  );
}
